### ISSUE TITLE
Problem running loading script

### ISSUE THREAD

**Issue by letitiabanana** [jacobswan1/ViTCAP#3]
I tried to run the loading script but cannot find the "./checkpoint/Logit_Vilt_captioning_testing_batch-size_512_encoder_vit_base_patch16_384_lr_1e-4_iter_60_vitbfocal20_bert_tokenizer_tags_ENC-DEC_multiplier_0.1_expand_tag-classifier_emb.pt" file

**Comment by letitiabanana** [comment]
Not contain in the download link https://seed.blob.core.windows.net/data/data/ViTCAP/checkpoint/Logit_Vilt_captioning_testing_batch-size_512_encoder_vit_base_patch16_384_lr_1e-4_iter_60_vitbfocal20_bert_tokenizer_tags_ENC-DEC_multiplier_0.1_expand_tag-classifier_emb.pt?sv=2020-10-02&st=2022-05-23T19%3A54%3A09Z&se=2032-05-24T19%3A54%3A00Z&sr=b&sp=r&sig=PW1KuGByuW0gZX%2BnEPXF3q1So0wN%2F3s9X7Scr5aZdDU%3D

**Comment by jacobswan1** [comment]
Hi there, I think this is caused by network issue as the downloading in my side is normal. Please try to access the link via VPN.
