### ISSUE TITLE
Thanks for your code. How can i make my own dataset in tsv format?

### ISSUE THREAD

**Issue by eenzeenee** [jacobswan1/ViTCAP#5]
I want to use your code to use it for my own dataset. 

I would like to know what code I can refer to to to make a tsv file. 

As far as I know, the MS-COCO dataset is also the original json file. 

I wonder what kind of process you went through to convert this into tsv.

Thank you again for your sharing.

**Comment by jacobswan1** [comment]
Hi! 

So TSV is the standard data format used in Microsoft and and datasets are all stored in this format so I did not process these dataset myself. TSV format is the same as csv, where you need to maintain each row for example contains: image_idx, image_string after encoding. 
To encode the image as string, this is the code: https://github.com/jacobswan1/ViTCAP/blob/3cf989aacda84872920321ac7d5f612312f550c1/src/tools/common.py#L23. 

Another file you need is *.lineidx file, which records the start/end position in memory of each row for .tsv file and so the access to each row will be fast. 

I think this function might be helpful: https://github.com/jacobswan1/ViTCAP/blob/3cf989aacda84872920321ac7d5f612312f550c1/src/tools/tsv/tsv_io.py#L891

I can't guarantee it helps to generate the tsv and lineidx successfully but functions needed for tsv files are mostly in /src/tools/tsv/tsv_io.py.

 I think one way you can try out is to make your customized data the same as COCO. This indeed will take some time.

**Comment by eenzeenee** [comment]
Thank you very much for your comment. I'll take that into consideration and experiment!
